name: blocfreezed
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.2
  flutter_bloc: ^8.0.1
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  retrofit: ^3.0.1+1
  retrofit_generator: ^4.0.1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0






flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
